import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";

const API=import.meta.env.VITE_API_URL||"http://localhost:4000/api";
async function api(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error(await r.text());return r.headers.get("content-type")?.includes("application/json")?r.json():r.blob()}

function Layout({page,setPage}){const nav=["Dashboard","Customers","Quotations","Invoices","Receipts","Expenses"];return <div><header><div className="brand">MICRO PAY</div><nav>{nav.map(n=><button className={page===n?"active":""} onClick={()=>setPage(n)}>{n}</button>)}</nav></header><main>{page==="Dashboard"?<Dashboard/>:page==="Customers"?<Customers/>:page==="Quotations"?<Quotations/>:page==="Invoices"?<Invoices/>:page==="Receipts"?<Receipts/>:<Expenses/>}</main></div>}

function Dashboard(){const [s,setS]=useState(null);useEffect(()=>{api("/dashboard").then(setS)},[]);if(!s)return <p>Loading...</p>;return <><h1>Business Dashboard</h1><div className="cards">{Object.entries(s).map(([k,v])=><div className="card"><small>{k.replace("_"," ").toUpperCase()}</small><strong>{["collected","expenses","outstanding"].includes(k)?"$"+Number(v).toLocaleString():v}</strong></div>)}</div><section className="panel"><h2>Micro Pay Automation</h2><p>Customer → Quotation → Invoice → Payment → Receipt</p><p>Enter transaction data once. The system carries it through the entire document workflow.</p></section></>}

function Customers(){const [rows,setRows]=useState([]);const [open,setOpen]=useState(false);const [f,setF]=useState({});const load=()=>api("/customers").then(setRows);useEffect(load,[]);const save=async e=>{e.preventDefault();await api("/customers",{method:"POST",body:JSON.stringify(f)});setOpen(false);setF({});load()};return <><div className="toolbar"><h1>Customers</h1><button onClick={()=>setOpen(true)}>+ New Customer</button></div>{open&&<Form fields={["name","contact_person","phone","email","address"]} values={f} setValues={setF} onSubmit={save}/>}<Table cols={["customer_code","name","contact_person","phone","email"]} rows={rows}/></>}

function Quotations(){const [rows,setRows]=useState([]);const [customers,setCustomers]=useState([]);const [open,setOpen]=useState(false);const [f,setF]=useState({items:[{description:"",quantity:1,unit_price:0}]});const load=()=>api("/quotations").then(setRows);useEffect(()=>{load();api("/customers").then(setCustomers)},[]);const save=async e=>{e.preventDefault();await api("/quotations",{method:"POST",body:JSON.stringify({...f,quote_date:new Date().toISOString().slice(0,10)})});setOpen(false);load()};const convert=async id=>{await api(`/quotations/${id}/convert`,{method:"POST"});load()};return <><div className="toolbar"><h1>Quotations</h1><button onClick={()=>setOpen(true)}>+ New Quotation</button></div>{open&&<div className="panel"><h2>New Quotation</h2><select onChange={e=>setF({...f,customer_id:e.target.value})}><option>Select customer</option>{customers.map(c=><option value={c.id}>{c.name}</option>)}</select>{f.items.map((x,i)=><div className="item"><input placeholder="Description" value={x.description} onChange={e=>{let a=[...f.items];a[i].description=e.target.value;setF({...f,items:a})}}/><input type="number" placeholder="Qty" value={x.quantity} onChange={e=>{let a=[...f.items];a[i].quantity=e.target.value;setF({...f,items:a})}}/><input type="number" placeholder="Unit price" value={x.unit_price} onChange={e=>{let a=[...f.items];a[i].unit_price=e.target.value;setF({...f,items:a})}}/></div>)}<button onClick={()=>setF({...f,items:[...f.items,{description:"",quantity:1,unit_price:0}]})}>+ Item</button> <button onClick={save}>Save Quotation</button></div>}<Table cols={["number","customer_name","quote_date","total","status"]} rows={rows} actions={r=><><a href={`${API}/documents/quotation/${r.id}.pdf`} target="_blank">PDF</a>{r.status!=="CONVERTED"&&<button onClick={()=>convert(r.id)}>Convert to Invoice</button>}</>}/></>}

function Invoices(){const [rows,setRows]=useState([]);const [pay,setPay]=useState(null);const load=()=>api("/invoices").then(setRows);useEffect(load,[]);const save=async e=>{e.preventDefault();const fd=new FormData(e.target);await api(`/invoices/${pay.id}/payments`,{method:"POST",body:JSON.stringify({payment_date:fd.get("date"),amount:fd.get("amount"),method:fd.get("method")})});setPay(null);load()};return <><h1>Invoices</h1>{pay&&<div className="panel"><h2>Payment — {pay.number}</h2><p>Balance: ${Number(pay.balance).toFixed(2)}</p><form onSubmit={save}><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="amount" type="number" step="0.01" max={pay.balance} required/><select name="method"><option>Cash</option><option>Bank Transfer</option><option>Mobile Money</option><option>Cheque</option></select><button>Record Payment</button></form></div>}<Table cols={["number","customer_name","invoice_date","total","paid","balance","status"]} rows={rows} actions={r=><><a href={`${API}/documents/invoice/${r.id}.pdf`} target="_blank">PDF</a>{Number(r.balance)>0&&<button onClick={()=>setPay(r)}>Payment</button>}</>}/></>}

function Receipts(){const [rows,setRows]=useState([]);useEffect(()=>{api("/receipts").then(setRows)},[]);return <><h1>Receipts</h1><Table cols={["receipt_number","customer_name","invoice_number","payment_date","amount","method"]} rows={rows} actions={r=><a href={`${API}/documents/receipt/${r.id}.pdf`} target="_blank">PDF</a>}/></>}

function Expenses(){const [rows,setRows]=useState([]);const [open,setOpen]=useState(false);const load=()=>api("/expenses").then(setRows);useEffect(load,[]);const save=async e=>{e.preventDefault();const fd=new FormData(e.target);const o=Object.fromEntries(fd);await api("/expenses",{method:"POST",body:JSON.stringify(o)});setOpen(false);load()};return <><div className="toolbar"><h1>Operational Expenses</h1><button onClick={()=>setOpen(true)}>+ Record Expense</button></div>{open&&<div className="panel"><form onSubmit={save}><input name="expense_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><select name="category"><option>Fuel</option><option>Water</option><option>Transport</option><option>Office Supplies</option><option>Repairs & Maintenance</option><option>Casual Labour</option><option>Communication</option><option>Other</option></select><input name="description" placeholder="Description" required/><input name="supplier" placeholder="Supplier"/><input name="amount" type="number" step="0.01" placeholder="Amount" required/><input name="payment_method" placeholder="Payment method"/><input name="paid_by" placeholder="Paid by"/><button>Record Expense</button></form></div>}<Table cols={["expense_number","expense_date","category","description","amount"]} rows={rows}/></>}

function Form({fields,values,setValues,onSubmit}){return <div className="panel"><form onSubmit={onSubmit}>{fields.map(k=><input placeholder={k.replace("_"," ")} required={k==="name"} value={values[k]||""} onChange={e=>setValues({...values,[k]:e.target.value})}/>) }<button>Save</button></form></div>}
function Table({cols,rows,actions}){return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th>{c.replace("_"," ")}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map(r=><tr>{cols.map(c=><td>{typeof r[c]==="number"||["total","paid","balance","amount"].includes(c)?Number(r[c]||0).toFixed(2):r[c]}</td>)}{actions&&<td className="actions">{actions(r)}</td>}</tr>)}</tbody></table></div>}

function App(){const [page,setPage]=useState("Dashboard");return <Layout page={page} setPage={setPage}/>};createRoot(document.getElementById("root")).render(<App/>);
