import { Router } from "express";
import { query } from "../db.js";
const router=Router(),one=async(s,p=[])=>((await query(s,p)).rows[0]||{}),rows=async(s,p=[])=>(await query(s,p)).rows;
const exists=async t=>!!(await one("SELECT to_regclass($1) IS NOT NULL ok",[`public.${t}`])).ok;
const range=(p="month")=>{const e=new Date(),s=new Date(e);if(p==="today")s.setHours(0,0,0,0);else if(p==="week")s.setDate(s.getDate()-6);else if(p==="quarter")s.setMonth(s.getMonth()-2,1);else if(p==="year")s.setMonth(0,1);else s.setDate(1);return{from:s.toISOString().slice(0,10),to:e.toISOString().slice(0,10)}};
async function finance(from,to){const [i,c,e,r,top,age]=await Promise.all([one("SELECT COALESCE(SUM(total),0) total FROM invoices WHERE invoice_date BETWEEN $1 AND $2 AND status<>'CANCELLED'",[from,to]),one("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE payment_date BETWEEN $1 AND $2 AND status='ISSUED'",[from,to]),one("SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date BETWEEN $1 AND $2 AND status<>'CANCELLED'",[from,to]),one("SELECT COALESCE(SUM(balance),0) total FROM invoices WHERE balance>0 AND status<>'CANCELLED'"),rows("SELECT c.name,COALESCE(SUM(i.balance),0) amount FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.balance>0 AND i.status<>'CANCELLED' GROUP BY c.id,c.name ORDER BY amount DESC LIMIT 10"),rows(`SELECT CASE WHEN CURRENT_DATE-COALESCE(due_date,invoice_date)<=0 THEN 'Current' WHEN CURRENT_DATE-COALESCE(due_date,invoice_date)<=30 THEN '1-30 days' WHEN CURRENT_DATE-COALESCE(due_date,invoice_date)<=60 THEN '31-60 days' WHEN CURRENT_DATE-COALESCE(due_date,invoice_date)<=90 THEN '61-90 days' ELSE '90+ days' END bucket,COALESCE(SUM(balance),0) amount FROM invoices WHERE balance>0 AND status<>'CANCELLED' GROUP BY 1`)]);const invoiced=+i.total||0,collected=+c.total||0,expenses=+e.total||0,receivables=+r.total||0;return{kpis:{invoiced,collected,expenses,receivables,net_cash:collected-expenses,collection_rate:invoiced?collected/invoiced*100:0},top_receivables:top,aging:age}}
async function hr(){if(!(await exists("hr_employees")))return{available:false};const employees=await one("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE active)::int active,COUNT(*) FILTER(WHERE employment_status='PROBATION')::int probation,COUNT(*) FILTER(WHERE employment_status='ON_LEAVE')::int on_leave FROM hr_employees");let contracts={active:0,expiring_60_days:0};if(await exists("hr_contracts"))contracts=await one("SELECT COUNT(*) FILTER(WHERE status='ACTIVE')::int active,COUNT(*) FILTER(WHERE status='ACTIVE' AND end_date BETWEEN CURRENT_DATE AND CURRENT_DATE+INTERVAL '60 days')::int expiring_60_days FROM hr_contracts");return{available:true,employees,contracts}}
const count=async t=>(await exists(t))?+(await one(`SELECT COUNT(*)::int count FROM ${t}`)).count:null;
const insights=(f,h)=>{const a=[],k=f.kpis,old=f.aging.find(x=>x.bucket==="90+ days");if(k.receivables>0)a.push({severity:"medium",area:"Finance",title:"Outstanding receivables",message:`Receivables total ${k.receivables.toFixed(2)}.`});if(+old?.amount>0)a.push({severity:"high",area:"Finance",title:"Receivables over 90 days",message:`${(+old.amount).toFixed(2)} is over 90 days overdue.`});if(k.expenses>k.collected&&k.collected>0)a.push({severity:"high",area:"Finance",title:"Expenses exceed collections",message:`Expenses exceed collections by ${(k.expenses-k.collected).toFixed(2)}.`});if(h.available&&+h.contracts.expiring_60_days>0)a.push({severity:"medium",area:"HR",title:"Contracts expiring",message:`${h.contracts.expiring_60_days} contract(s) expire within 60 days.`});return a.length?a:[{severity:"low",area:"Business",title:"No major exceptions",message:"No configured exception threshold was triggered."}]};
router.get("/analytics/executive",async(req,res)=>{try{const p=range(req.query.period),f=await finance(p.from,p.to),h=await hr();res.json({period:p,finance:f,hr:h,operations:{suppliers:await count("suppliers"),purchase_orders:await count("purchase_orders"),goods_receipts:await count("goods_receipts"),inventory_items:await count("inventory_items")},insights:insights(f,h)})}catch(e){res.status(500).json({error:"Unable to load executive analytics",detail:e.message})}});
router.post("/analytics/ask",async(req,res)=>{try{const q0=String(req.body?.question||"").trim();if(!q0)return res.status(400).json({error:"Question is required"});const p=range(req.body?.period),f=await finance(p.from,p.to),h=await hr(),q=q0.toLowerCase();let answer="",source=[];if(/owe|receivable|outstanding|debtor/.test(q)){answer=f.top_receivables.length?`Largest outstanding customer: ${f.top_receivables[0].name}, ${(+f.top_receivables[0].amount).toFixed(2)}. Total receivables: ${f.kpis.receivables.toFixed(2)}.`:"No outstanding customer balances.";source=["invoices","customers"]}else if(/expense|spend|cost/.test(q)){answer=`Expenses: ${f.kpis.expenses.toFixed(2)}.`;source=["expenses"]}else if(/revenue|invoice|sales/.test(q)){answer=`Invoiced: ${f.kpis.invoiced.toFixed(2)}. Collected: ${f.kpis.collected.toFixed(2)}. Collection rate: ${f.kpis.collection_rate.toFixed(1)}%.`;source=["invoices","payments"]}else if(/cash|collection/.test(q)){answer=`Collections: ${f.kpis.collected.toFixed(2)}. Expenses: ${f.kpis.expenses.toFixed(2)}. Net cash movement: ${f.kpis.net_cash.toFixed(2)}.`;source=["payments","expenses"]}else if(/employee|staff|headcount|contract|hr|payroll/.test(q)){answer=h.available?`Employees: ${h.employees.total}; active: ${h.employees.active}; probation: ${h.employees.probation}; on leave: ${h.employees.on_leave}; contracts expiring within 60 days: ${h.contracts.expiring_60_days||0}.`:"HR data unavailable.";source=["hr_employees","hr_contracts"]}else{answer="I can analyse revenue, collections, receivables, expenses, cash movement, customer debt and HR workforce indicators.";source=["controlled analytics layer"]}res.json({question:q0,period:p,answer,source,mode:"controlled-read-only"})}catch(e){res.status(500).json({error:"Unable to analyse question",detail:e.message})}});
export default router;
