import { Router } from "express";
import { query, transaction } from "../db.js";
import { authorizeLegacyOrPermission } from "../middleware/permissions.js";

const router = Router();
const allow = (req,res,roles=[]) => authorizeLegacyOrPermission(req,res,roles);
const clean = v => String(v ?? "").trim();
const nullable = v => clean(v) || null;
const audit = (client,userId,action,entityType,entityId,details={}) => client.query(
  "INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5)",
  [userId||null,action,entityType,entityId||null,JSON.stringify(details)]
);

router.get("/hr/dashboard",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const [head,dept,contracts]=await Promise.all([
  query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE active AND employment_status IN ('ACTIVE','PROBATION','ON_LEAVE'))::int active,COUNT(*) FILTER(WHERE employment_status='PROBATION')::int probation,COUNT(*) FILTER(WHERE employment_status='ON_LEAVE')::int on_leave FROM hr_employees`),
  query(`SELECT d.id,d.name,COUNT(e.id)::int employee_count FROM hr_departments d LEFT JOIN hr_employees e ON e.department_id=d.id AND e.active GROUP BY d.id,d.name ORDER BY d.name`),
  query(`SELECT COUNT(*) FILTER(WHERE status='ACTIVE')::int active,COUNT(*) FILTER(WHERE status='ACTIVE' AND end_date BETWEEN CURRENT_DATE AND CURRENT_DATE+INTERVAL '60 days')::int expiring_60_days FROM hr_contracts`)
]);res.json({employees:head.rows[0],departments:dept.rows,contracts:contracts.rows[0]})}catch(e){res.status(500).json({error:e.message})}});

router.get("/hr/departments",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{res.json((await query(`SELECT d.*,COUNT(e.id)::int employee_count FROM hr_departments d LEFT JOIN hr_employees e ON e.department_id=d.id AND e.active GROUP BY d.id ORDER BY d.name`)).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/hr/departments",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`INSERT INTO hr_departments(code,name,description,created_by) VALUES($1,$2,$3,$4) RETURNING *`,[clean(req.body.code).toUpperCase(),clean(req.body.name),nullable(req.body.description),req.user.id]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch("/hr/departments/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`UPDATE hr_departments SET code=$1,name=$2,description=$3,active=COALESCE($4,active),updated_at=NOW() WHERE id=$5 RETURNING *`,[clean(req.body.code).toUpperCase(),clean(req.body.name),nullable(req.body.description),req.body.active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Department not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/hr/positions",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{res.json((await query(`SELECT p.*,d.name department_name FROM hr_positions p LEFT JOIN hr_departments d ON d.id=p.department_id ORDER BY p.title`)).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/hr/positions",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`INSERT INTO hr_positions(code,title,department_id,description,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[clean(req.body.code).toUpperCase(),clean(req.body.title),req.body.department_id||null,nullable(req.body.description),req.user.id]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch("/hr/positions/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`UPDATE hr_positions SET code=$1,title=$2,department_id=$3,description=$4,active=COALESCE($5,active),updated_at=NOW() WHERE id=$6 RETURNING *`,[clean(req.body.code).toUpperCase(),clean(req.body.title),req.body.department_id||null,nullable(req.body.description),req.body.active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Position not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/hr/employees",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`SELECT e.*,concat_ws(' ',e.first_name,e.middle_name,e.last_name) full_name,d.name department_name,p.title position_title,concat_ws(' ',s.first_name,s.last_name) supervisor_name FROM hr_employees e LEFT JOIN hr_departments d ON d.id=e.department_id LEFT JOIN hr_positions p ON p.id=e.position_id LEFT JOIN hr_employees s ON s.id=e.supervisor_id ORDER BY e.employee_no`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
router.get("/hr/employees/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const employee=(await query(`SELECT e.*,concat_ws(' ',e.first_name,e.middle_name,e.last_name) full_name,d.name department_name,p.title position_title FROM hr_employees e LEFT JOIN hr_departments d ON d.id=e.department_id LEFT JOIN hr_positions p ON p.id=e.position_id WHERE e.id=$1`,[req.params.id])).rows[0];if(!employee)return res.status(404).json({error:"Employee not found"});const [contracts,contacts,documents,history]=await Promise.all([query("SELECT * FROM hr_contracts WHERE employee_id=$1 ORDER BY start_date DESC",[req.params.id]),query("SELECT * FROM hr_emergency_contacts WHERE employee_id=$1 ORDER BY is_primary DESC,name",[req.params.id]),query("SELECT * FROM hr_employee_documents WHERE employee_id=$1 ORDER BY created_at DESC",[req.params.id]),query("SELECT * FROM hr_employment_history WHERE employee_id=$1 ORDER BY effective_date DESC,created_at DESC",[req.params.id])]);res.json({...employee,contracts:contracts.rows,emergency_contacts:contacts.rows,documents:documents.rows,history:history.rows})}catch(e){res.status(500).json({error:e.message})}});
router.post("/hr/employees",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{if(!clean(req.body.employee_no)||!clean(req.body.first_name)||!clean(req.body.last_name)||!req.body.hire_date)return res.status(400).json({error:"Employee number, first name, last name and hire date are required"});const result=await transaction(async c=>{const r=await c.query(`INSERT INTO hr_employees(employee_no,first_name,middle_name,last_name,gender,date_of_birth,nationality,phone,email,address,department_id,position_id,supervisor_id,user_id,employment_type,employment_status,hire_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`,[clean(req.body.employee_no).toUpperCase(),clean(req.body.first_name),nullable(req.body.middle_name),clean(req.body.last_name),nullable(req.body.gender),req.body.date_of_birth||null,nullable(req.body.nationality),nullable(req.body.phone),nullable(req.body.email),nullable(req.body.address),req.body.department_id||null,req.body.position_id||null,req.body.supervisor_id||null,req.body.user_id||null,req.body.employment_type||"FULL_TIME",req.body.employment_status||"ACTIVE",req.body.hire_date,nullable(req.body.notes),req.user.id]);await audit(c,req.user.id,"CREATE","HR_EMPLOYEE",r.rows[0].id,{employee_no:r.rows[0].employee_no});await c.query(`INSERT INTO hr_employment_history(employee_id,event_type,effective_date,new_value,created_by) VALUES($1,'HIRED',$2,$3,$4)`,[r.rows[0].id,req.body.hire_date,JSON.stringify({department_id:req.body.department_id||null,position_id:req.body.position_id||null,status:req.body.employment_status||"ACTIVE"}),req.user.id]);return r.rows[0]});res.status(201).json(result)}catch(e){res.status(400).json({error:e.message})}});
router.patch("/hr/employees/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const result=await transaction(async c=>{const before=(await c.query("SELECT * FROM hr_employees WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!before)throw new Error("Employee not found");const r=await c.query(`UPDATE hr_employees SET employee_no=$1,first_name=$2,middle_name=$3,last_name=$4,gender=$5,date_of_birth=$6,nationality=$7,phone=$8,email=$9,address=$10,department_id=$11,position_id=$12,supervisor_id=$13,user_id=$14,employment_type=$15,employment_status=$16,hire_date=$17,separation_date=$18,notes=$19,active=COALESCE($20,active),updated_at=NOW() WHERE id=$21 RETURNING *`,[clean(req.body.employee_no).toUpperCase(),clean(req.body.first_name),nullable(req.body.middle_name),clean(req.body.last_name),nullable(req.body.gender),req.body.date_of_birth||null,nullable(req.body.nationality),nullable(req.body.phone),nullable(req.body.email),nullable(req.body.address),req.body.department_id||null,req.body.position_id||null,req.body.supervisor_id||null,req.body.user_id||null,req.body.employment_type||before.employment_type,req.body.employment_status||before.employment_status,req.body.hire_date||before.hire_date,req.body.separation_date||null,nullable(req.body.notes),req.body.active,req.params.id]);const after=r.rows[0];if(before.department_id!==after.department_id||before.position_id!==after.position_id||before.employment_status!==after.employment_status){await c.query(`INSERT INTO hr_employment_history(employee_id,event_type,effective_date,old_value,new_value,created_by) VALUES($1,'EMPLOYMENT_CHANGE',CURRENT_DATE,$2,$3,$4)`,[after.id,JSON.stringify({department_id:before.department_id,position_id:before.position_id,status:before.employment_status}),JSON.stringify({department_id:after.department_id,position_id:after.position_id,status:after.employment_status}),req.user.id])}await audit(c,req.user.id,"UPDATE","HR_EMPLOYEE",after.id,{employee_no:after.employee_no});return after});res.json(result)}catch(e){res.status(e.message==="Employee not found"?404:400).json({error:e.message})}});

router.get("/hr/contracts",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{res.json((await query(`SELECT c.*,e.employee_no,concat_ws(' ',e.first_name,e.middle_name,e.last_name) employee_name FROM hr_contracts c JOIN hr_employees e ON e.id=c.employee_id ORDER BY c.start_date DESC`)).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/hr/contracts",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{if(!req.body.employee_id||!req.body.start_date)return res.status(400).json({error:"Employee and contract start date are required"});const r=await transaction(async c=>{const x=(await c.query(`INSERT INTO hr_contracts(employee_id,contract_type,start_date,end_date,probation_end_date,salary,currency_code,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.body.employee_id,req.body.contract_type||"PERMANENT",req.body.start_date,req.body.end_date||null,req.body.probation_end_date||null,req.body.salary===""||req.body.salary==null?null:Number(req.body.salary),clean(req.body.currency_code||"USD").toUpperCase(),req.body.status||"ACTIVE",nullable(req.body.notes),req.user.id])).rows[0];await audit(c,req.user.id,"CREATE","HR_CONTRACT",x.id,{employee_id:x.employee_id});return x});res.status(201).json(r)}catch(e){res.status(400).json({error:e.message})}});
router.patch("/hr/contracts/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`UPDATE hr_contracts SET contract_type=$1,start_date=$2,end_date=$3,probation_end_date=$4,salary=$5,currency_code=$6,status=$7,notes=$8,updated_at=NOW() WHERE id=$9 RETURNING *`,[req.body.contract_type,req.body.start_date,req.body.end_date||null,req.body.probation_end_date||null,req.body.salary===""||req.body.salary==null?null:Number(req.body.salary),clean(req.body.currency_code||"USD").toUpperCase(),req.body.status,nullable(req.body.notes),req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Contract not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

export default router;
