import { Router } from "express";
import { query, transaction } from "../db.js";
import { nextNumber } from "../utils/sequence.js";
import { authorizeLegacyOrPermission } from "../middleware/permissions.js";

const router = Router();
const allow = (req,res,roles=[]) => authorizeLegacyOrPermission(req,res,roles);
const audit = (client,userId,action,entityType,entityId,details={}) => client.query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5)",[userId||null,action,entityType,entityId||null,JSON.stringify(details)]);
const openPeriod = async (client,date) => {
  const r=await client.query(`SELECT status FROM financial_periods WHERE period_year=EXTRACT(YEAR FROM $1::date)::int AND period_month=EXTRACT(MONTH FROM $1::date)::int`,[date]);
  if(!r.rowCount) throw new Error("No financial period is configured for the selected date");
  if(String(r.rows[0].status).toUpperCase()!=="OPEN") throw new Error("The selected date belongs to a closed financial period");
};
const items = a => (Array.isArray(a)?a:[]).map(x=>({item_id:String(x.item_id||""),quantity:Number(x.quantity),unit_cost:Number(x.unit_cost||0),notes:String(x.notes||"")})).filter(x=>x.item_id&&x.quantity>0&&x.unit_cost>=0);

router.get("/inventory/categories",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER","FINANCE"]))return;try{res.json((await query("SELECT * FROM inventory_categories ORDER BY name")).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/categories",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query("INSERT INTO inventory_categories(code,name,description) VALUES($1,$2,$3) RETURNING *",[String(req.body.code||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.description||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch("/inventory/categories/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query("UPDATE inventory_categories SET code=$1,name=$2,description=$3,active=COALESCE($4,active),updated_at=NOW() WHERE id=$5 RETURNING *",[String(req.body.code||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.description||null,req.body.active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Category not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/uoms",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json((await query("SELECT * FROM units_of_measure ORDER BY name")).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/uoms",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query("INSERT INTO units_of_measure(code,name,decimal_places) VALUES($1,$2,$3) RETURNING *",[String(req.body.code||"").trim().toUpperCase(),String(req.body.name||"").trim(),Number(req.body.decimal_places||0)]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/warehouses",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json((await query("SELECT w.*,u.name manager_name FROM warehouses w LEFT JOIN users u ON u.id=w.manager_id ORDER BY w.name")).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/warehouses",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query("INSERT INTO warehouses(code,name,location,manager_id) VALUES($1,$2,$3,$4) RETURNING *",[String(req.body.code||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.location||null,req.body.manager_id||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch("/inventory/warehouses/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query("UPDATE warehouses SET code=$1,name=$2,location=$3,manager_id=$4,active=COALESCE($5,active),updated_at=NOW() WHERE id=$6 RETURNING *",[String(req.body.code||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.location||null,req.body.manager_id||null,req.body.active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Warehouse not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/items",async(req,res)=>{if(!allow(req,res,[]))return;try{const r=await query(`SELECT i.*,c.name category_name,u.code uom_code FROM inventory_items i LEFT JOIN inventory_categories c ON c.id=i.category_id LEFT JOIN units_of_measure u ON u.id=i.base_uom_id ORDER BY i.name`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/items",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`INSERT INTO inventory_items(sku,name,category_id,base_uom_id,item_type,standard_cost,reorder_level,reorder_quantity,description,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[String(req.body.sku||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.category_id||null,req.body.base_uom_id,req.body.item_type||"STOCK",Number(req.body.standard_cost||0),Number(req.body.reorder_level||0),Number(req.body.reorder_quantity||0),req.body.description||null,req.user.id]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch("/inventory/items/:id",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`UPDATE inventory_items SET sku=$1,name=$2,category_id=$3,base_uom_id=$4,item_type=$5,standard_cost=$6,reorder_level=$7,reorder_quantity=$8,description=$9,active=COALESCE($10,active),updated_at=NOW() WHERE id=$11 RETURNING *`,[String(req.body.sku||"").trim().toUpperCase(),String(req.body.name||"").trim(),req.body.category_id||null,req.body.base_uom_id,req.body.item_type||"STOCK",Number(req.body.standard_cost||0),Number(req.body.reorder_level||0),Number(req.body.reorder_quantity||0),req.body.description||null,req.body.active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Inventory item not found"});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/item-warehouses/:itemId",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json((await query(`SELECT iw.*,w.code warehouse_code,w.name warehouse_name FROM inventory_item_warehouses iw JOIN warehouses w ON w.id=iw.warehouse_id WHERE iw.item_id=$1 ORDER BY w.name`,[req.params.itemId])).rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/item-warehouses",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await query(`INSERT INTO inventory_item_warehouses(item_id,warehouse_id,reorder_level,reorder_quantity,min_stock,max_stock) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(item_id,warehouse_id) DO UPDATE SET reorder_level=EXCLUDED.reorder_level,reorder_quantity=EXCLUDED.reorder_quantity,min_stock=EXCLUDED.min_stock,max_stock=EXCLUDED.max_stock,active=TRUE RETURNING *`,[req.body.item_id,req.body.warehouse_id,Number(req.body.reorder_level||0),Number(req.body.reorder_quantity||0),Number(req.body.min_stock||0),req.body.max_stock===""?null:Number(req.body.max_stock)]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/balances",async(req,res)=>{if(!allow(req,res,[]))return;try{const r=await query(`SELECT b.*,i.sku,i.name item_name,w.code warehouse_code,w.name warehouse_name,u.code uom_code FROM inventory_stock_balances b JOIN inventory_items i ON i.id=b.item_id JOIN warehouses w ON w.id=b.warehouse_id JOIN units_of_measure u ON u.id=i.base_uom_id ORDER BY i.name,w.name`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
router.get("/inventory/transactions",async(req,res)=>{if(!allow(req,res,[]))return;try{const r=await query(`SELECT t.*,i.sku,i.name item_name,w.name warehouse_name FROM inventory_transactions t JOIN inventory_items i ON i.id=t.item_id JOIN warehouses w ON w.id=t.warehouse_id ORDER BY t.created_at DESC LIMIT 500`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});

async function postMovement(client,{itemId,warehouseId,delta,unitCost,type,date,sourceType,sourceId,userId}){
  const bal=(await client.query("SELECT * FROM inventory_stock_balances WHERE item_id=$1 AND warehouse_id=$2 FOR UPDATE",[itemId,warehouseId])).rows[0];
  const current=bal?Number(bal.quantity_on_hand):0; const next=current+Number(delta);
  if(next<0) throw new Error("Insufficient stock for this transaction");
  if(bal) await client.query("UPDATE inventory_stock_balances SET quantity_on_hand=$1,average_unit_cost=$2,last_movement_at=NOW() WHERE id=$3",[next,Number(unitCost||bal.average_unit_cost||0),bal.id]);
  else await client.query("INSERT INTO inventory_stock_balances(item_id,warehouse_id,quantity_on_hand,average_unit_cost,last_movement_at) VALUES($1,$2,$3,$4,NOW())",[itemId,warehouseId,next,Number(unitCost||0)]);
  const no=await nextNumber(client,"ITX");
  await client.query(`INSERT INTO inventory_transactions(transaction_no,transaction_type,item_id,warehouse_id,quantity_change,unit_cost,total_cost,source_type,source_id,transaction_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[no,type,itemId,warehouseId,delta,Number(unitCost||0),Math.abs(Number(delta))*Number(unitCost||0),sourceType||null,sourceId||null,date,userId]);
}

async function listDocs(table,itemTable,idCol,extra=""){
  const r=await query(`SELECT d.*,w.name warehouse_name,COALESCE(SUM(di.quantity),0)::numeric total_quantity,COUNT(di.id)::int item_count FROM ${table} d JOIN warehouses w ON w.id=d.warehouse_id LEFT JOIN ${itemTable} di ON di.${idCol}=d.id ${extra} GROUP BY d.id,w.name ORDER BY d.created_at DESC`);return r.rows;
}
router.get("/inventory/receipts",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json(await listDocs("stock_receipts","stock_receipt_items","receipt_id"))}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/receipts",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;const clean=items(req.body.items);if(!req.body.warehouse_id||!req.body.receipt_date||!clean.length)return res.status(400).json({error:"Warehouse, receipt date and at least one item are required"});try{const r=await transaction(async c=>{await openPeriod(c,req.body.receipt_date);const no=await nextNumber(c,"SR");const h=(await c.query(`INSERT INTO stock_receipts(number,warehouse_id,receipt_date,source_type,source_id,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[no,req.body.warehouse_id,req.body.receipt_date,req.body.source_type||null,req.body.source_id||null,req.body.notes||null,req.user.id])).rows[0];for(const x of clean)await c.query("INSERT INTO stock_receipt_items(receipt_id,item_id,quantity,unit_cost,notes) VALUES($1,$2,$3,$4,$5)",[h.id,x.item_id,x.quantity,x.unit_cost,x.notes]);await audit(c,req.user.id,"CREATE","STOCK_RECEIPT",h.id,{number:no});return h});res.status(201).json(r)}catch(e){res.status(400).json({error:e.message})}});
router.post("/inventory/receipts/:id/post",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await transaction(async c=>{const h=(await c.query("SELECT * FROM stock_receipts WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!h)throw new Error("Stock receipt not found");if(h.status!=="DRAFT")throw new Error("Only draft receipts can be posted");await openPeriod(c,h.receipt_date);const its=(await c.query("SELECT * FROM stock_receipt_items WHERE receipt_id=$1",[h.id])).rows;if(!its.length)throw new Error("Receipt has no items");for(const x of its)await postMovement(c,{itemId:x.item_id,warehouseId:h.warehouse_id,delta:x.quantity,unitCost:x.unit_cost,type:"RECEIPT",date:h.receipt_date,sourceType:"STOCK_RECEIPT",sourceId:h.id,userId:req.user.id});const u=(await c.query("UPDATE stock_receipts SET status='POSTED',posted_by=$1,posted_at=NOW(),updated_at=NOW() WHERE id=$2 RETURNING *",[req.user.id,h.id])).rows[0];await audit(c,req.user.id,"POST","STOCK_RECEIPT",h.id,{number:h.number});return u});res.json(r)}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/issues",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json(await listDocs("stock_issues","stock_issue_items","issue_id"))}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/issues",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;const clean=items(req.body.items);if(!req.body.warehouse_id||!req.body.issue_date||!req.body.purpose||!clean.length)return res.status(400).json({error:"Warehouse, issue date, purpose and items are required"});try{const r=await transaction(async c=>{await openPeriod(c,req.body.issue_date);const no=await nextNumber(c,"SI");const h=(await c.query(`INSERT INTO stock_issues(number,warehouse_id,issue_date,issued_to,purpose,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[no,req.body.warehouse_id,req.body.issue_date,req.body.issued_to||null,req.body.purpose,req.body.notes||null,req.user.id])).rows[0];for(const x of clean)await c.query("INSERT INTO stock_issue_items(issue_id,item_id,quantity,unit_cost,notes) VALUES($1,$2,$3,$4,$5)",[h.id,x.item_id,x.quantity,x.unit_cost,x.notes]);return h});res.status(201).json(r)}catch(e){res.status(400).json({error:e.message})}});
router.post("/inventory/issues/:id/post",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await transaction(async c=>{const h=(await c.query("SELECT * FROM stock_issues WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!h)throw new Error("Stock issue not found");if(h.status!=="DRAFT")throw new Error("Only draft issues can be posted");await openPeriod(c,h.issue_date);const its=(await c.query("SELECT * FROM stock_issue_items WHERE issue_id=$1",[h.id])).rows;if(!its.length)throw new Error("Issue has no items");for(const x of its)await postMovement(c,{itemId:x.item_id,warehouseId:h.warehouse_id,delta:-x.quantity,unitCost:x.unit_cost,type:"ISSUE",date:h.issue_date,sourceType:"STOCK_ISSUE",sourceId:h.id,userId:req.user.id});const u=(await c.query("UPDATE stock_issues SET status='POSTED',posted_by=$1,posted_at=NOW(),updated_at=NOW() WHERE id=$2 RETURNING *",[req.user.id,h.id])).rows[0];return u});res.json(r)}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/transfers",async(req,res)=>{if(!allow(req,res,[]))return;try{const r=await query(`SELECT d.*,wf.name from_warehouse_name,wt.name to_warehouse_name,COALESCE(SUM(di.quantity),0)::numeric total_quantity,COUNT(di.id)::int item_count FROM stock_transfers d JOIN warehouses wf ON wf.id=d.from_warehouse_id JOIN warehouses wt ON wt.id=d.to_warehouse_id LEFT JOIN stock_transfer_items di ON di.transfer_id=d.id GROUP BY d.id,wf.name,wt.name ORDER BY d.created_at DESC`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/transfers",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;const clean=items(req.body.items);if(!req.body.from_warehouse_id||!req.body.to_warehouse_id||req.body.from_warehouse_id===req.body.to_warehouse_id||!req.body.transfer_date||!clean.length)return res.status(400).json({error:"Different source/destination warehouses, date and items are required"});try{const r=await transaction(async c=>{await openPeriod(c,req.body.transfer_date);const no=await nextNumber(c,"ST");const h=(await c.query(`INSERT INTO stock_transfers(number,from_warehouse_id,to_warehouse_id,transfer_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[no,req.body.from_warehouse_id,req.body.to_warehouse_id,req.body.transfer_date,req.body.notes||null,req.user.id])).rows[0];for(const x of clean)await c.query("INSERT INTO stock_transfer_items(transfer_id,item_id,quantity,unit_cost,notes) VALUES($1,$2,$3,$4,$5)",[h.id,x.item_id,x.quantity,x.unit_cost,x.notes]);return h});res.status(201).json(r)}catch(e){res.status(400).json({error:e.message})}});
router.post("/inventory/transfers/:id/post",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await transaction(async c=>{const h=(await c.query("SELECT * FROM stock_transfers WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!h)throw new Error("Stock transfer not found");if(h.status!=="DRAFT")throw new Error("Only draft transfers can be posted");await openPeriod(c,h.transfer_date);const its=(await c.query("SELECT * FROM stock_transfer_items WHERE transfer_id=$1",[h.id])).rows;if(!its.length)throw new Error("Transfer has no items");for(const x of its){await postMovement(c,{itemId:x.item_id,warehouseId:h.from_warehouse_id,delta:-x.quantity,unitCost:x.unit_cost,type:"TRANSFER_OUT",date:h.transfer_date,sourceType:"STOCK_TRANSFER",sourceId:h.id,userId:req.user.id});await postMovement(c,{itemId:x.item_id,warehouseId:h.to_warehouse_id,delta:x.quantity,unitCost:x.unit_cost,type:"TRANSFER_IN",date:h.transfer_date,sourceType:"STOCK_TRANSFER",sourceId:h.id,userId:req.user.id});}return (await c.query("UPDATE stock_transfers SET status='POSTED',posted_by=$1,posted_at=NOW(),updated_at=NOW() WHERE id=$2 RETURNING *",[req.user.id,h.id])).rows[0]});res.json(r)}catch(e){res.status(400).json({error:e.message})}});

router.get("/inventory/adjustments",async(req,res)=>{if(!allow(req,res,[]))return;try{res.json(await listDocs("stock_adjustments","stock_adjustment_items","adjustment_id"))}catch(e){res.status(500).json({error:e.message})}});
router.post("/inventory/adjustments",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;const clean=(Array.isArray(req.body.items)?req.body.items:[]).map(x=>({item_id:String(x.item_id||""),quantity_delta:Number(x.quantity_delta),unit_cost:Number(x.unit_cost||0),notes:String(x.notes||"")})).filter(x=>x.item_id&&x.quantity_delta!==0&&x.unit_cost>=0);if(!req.body.warehouse_id||!req.body.adjustment_date||!req.body.reason||!clean.length)return res.status(400).json({error:"Warehouse, date, reason and adjustment items are required"});try{const r=await transaction(async c=>{await openPeriod(c,req.body.adjustment_date);const no=await nextNumber(c,"SA");const h=(await c.query(`INSERT INTO stock_adjustments(number,warehouse_id,adjustment_date,reason,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[no,req.body.warehouse_id,req.body.adjustment_date,req.body.reason,req.body.notes||null,req.user.id])).rows[0];for(const x of clean)await c.query("INSERT INTO stock_adjustment_items(adjustment_id,item_id,quantity_delta,unit_cost,notes) VALUES($1,$2,$3,$4,$5)",[h.id,x.item_id,x.quantity_delta,x.unit_cost,x.notes]);return h});res.status(201).json(r)}catch(e){res.status(400).json({error:e.message})}});
router.post("/inventory/adjustments/:id/post",async(req,res)=>{if(!allow(req,res,["ADMIN","MANAGER"]))return;try{const r=await transaction(async c=>{const h=(await c.query("SELECT * FROM stock_adjustments WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!h)throw new Error("Stock adjustment not found");if(h.status!=="DRAFT")throw new Error("Only draft adjustments can be posted");await openPeriod(c,h.adjustment_date);const its=(await c.query("SELECT * FROM stock_adjustment_items WHERE adjustment_id=$1",[h.id])).rows;if(!its.length)throw new Error("Adjustment has no items");for(const x of its)await postMovement(c,{itemId:x.item_id,warehouseId:h.warehouse_id,delta:x.quantity_delta,unitCost:x.unit_cost,type:x.quantity_delta>0?"ADJUSTMENT_IN":"ADJUSTMENT_OUT",date:h.adjustment_date,sourceType:"STOCK_ADJUSTMENT",sourceId:h.id,userId:req.user.id});return (await c.query("UPDATE stock_adjustments SET status='POSTED',posted_by=$1,posted_at=NOW(),updated_at=NOW() WHERE id=$2 RETURNING *",[req.user.id,h.id])).rows[0]});res.json(r)}catch(e){res.status(400).json({error:e.message})}});

export default router;
